define(["storage"], function(){
	FwBase.Wtf.Client.restServices["homeinfos"] = {
		GET_root : function(params) {
			return {
				"navList":[{"id":"010","code":"010","name":"Dashboard","icon":"icon-dashboard","url":"","collapse":"Y"},
				           {"id":"011","code":"011","name":"Samples","icon":"icon-dashboard","url":"","collapse":null},
				           {"id":"020","code":"020","name":"Devices","icon":"icon-question-sign","url":"","collapse":null},
				           {"id":"030","code":"030","name":"Device Templates","icon":"icon-briefcase","url":"","collapse":null},
				           {"id":"040","code":"040","name":"CLI Configlets","icon":"icon-briefcase","url":"","collapse":null},
				           {"id":"050","code":"050","name":"Images and Scripts","icon":"icon-exclamation-sign","url":"","collapse":null},
				           {"id":"060","code":"060","name":"Reports","icon":"icon-exclamation-sign","url":"","collapse":null},
				           {"id":"070","code":"070","name":"Network Monitoring","icon":"icon-legal","url":"","collapse":null},
				           {"id":"080","code":"080","name":"Configuration Files","icon":"icon-legal","url":"","collapse":null},
				           {"id":"090","code":"090","name":"Jobs","icon":"icon-comment","url":"","collapse":null},
				           {"id":"100","code":"100","name":"Users","icon":"icon-briefcase","url":"","collapse":null},
				           {"id":"110","code":"110","name":"Audit Logs","icon":"icon-briefcase","url":"","collapse":null},
				           {"id":"120","code":"120","name":"Administration","icon":"icon-briefcase","url":"","collapse":null},
				           {"name":"Dashboard","url":"wtfdocui/dashboard","groupId":"010","target":"Y"},
				           {"name":"My Favarite1","url":"wtf/charttest","groupId":"010","target":"Y"},
				           {"name":"My Favarite2","url":"wtf/buttontest","groupId":"010","target":"Y"},
				           {"name":"Buttons","url":"wtf/buttontest","groupId":"011","target":"Y"},
				           {"name":"Charts","url":"wtf/charttest","groupId":"011","target":"Y"},
				           {"name":"Design Test","url":"wtf/designtest","groupId":"011","target":"Y"},
				           {"name":"Images","url":"wtf/imagetest","groupId":"011","target":"Y"},
				           {"name":"Landing Page","url":"wtf/landingpage","groupId":"011","target":"Y"},
				           {"name":"Landing Page Tree","url":"wtf/landingpagetree","groupId":"011","target":"Y"},
				           {"name":"Input Components","url":"wtf/inputtest","groupId":"011","target":"Y"},
				           {"name":"Tab Layout","url":"wtf/tabtest","groupId":"011","target":"Y"},
				           {"name":"Forms","url":"wtf/formtest","groupId":"011","target":"Y"},
				           {"name":"Wizard Form","url":"wtf/wizardform","groupId":"011","target":"Y"},
				           {"name":"Device Management","url":"rest/devicemgr","groupId":"020","target":"Y"},
				           {"name":"Device Discovery","url":"rest/devicediscovery","groupId":"020","target":"Y"},
				           {"name":"Specify Probes","url":"rest/specifyprobes","groupId":"020","target":"Y"},
				           {"name":"Specify Credentials","url":"rest/specifycredentials","groupId":"020","target":"Y"},
				           {"name":"Deployed Devices","url":"rest/deploydevices","groupId":"020","target":"Y"},
				           {"name":"Unmanaged Devices","url":"rest/unmanageddevices","groupId":"020","target":"Y"},
				           {"name":"Secure Console","url":"rest/secureconsole","groupId":"020","target":"Y"},
				           {"name":"Device Adapter","url":"rest/deviceadapter","groupId":"020","target":"Y"},
				           {"name":"Audit Log","url":"rest/auditlog","groupId":"110","target":"Y"},
				           {"name":"Space Node Settings","url":"rest/snsettings","groupId":"120","target":"Y"},
				           {"name":"SNMP Manager","url":"rest/snmpmanager","groupId":"120","target":"Y"},
				           {"name":"Database Backup and Restore","url":"rest/dbandrestore","groupId":"120","target":"Y"},
				           {"name":"Licenses","url":"rest/licenses","groupId":"120","target":"Y"},
				           {"name":"Applications","url":"rest/applications","groupId":"120","target":"Y"},
				           {"name":"Space Troubleshootting","url":"rest/spacetroubleshootting","groupId":"120","target":"Y"},
				           {"name":"Platform Certificate","url":"rest/platform centificate","groupId":"120","target":"Y"},
				           {"name":"CA/CRL Certificates","url":"rest/cacrlcertificates","groupId":"120","target":"Y"},
				           {"name":"Authentication Servers","url":"rest/authenticationservers","groupId":"120","target":"Y"},
				           {"name":"SMTP Servers","url":"rest/smtpservers","groupId":"120","target":"Y"},
				           {"name":"Tags","url":"rest/tags","groupId":"120","target":"Y"},
				           {"name":"Permission Labels","url":"rest/permissionlabels","groupId":"120","target":"Y"},
				           {"name":"DMI Schemas","url":"rest/dmischemas","groupId":"120","target":"Y"},
				           {"name":"Definitions","url":"rest/definitions","groupId":"030","target":"Y"},
				           {"name":"Templates","url":"rest/templates","groupId":"030","target":"Y"},
				           {"name":"Configlets","url":"rest/configlets","groupId":"040","target":"Y"},
				           {"name":"Configuration View","url":"rest/configurationview","groupId":"040","target":"Y"},
				           {"name":"Xpath and Regex","url":"rest/xpathandregex","groupId":"040","target":"Y"},
				           {"name":"Images","url":"rest/images","groupId":"050","target":"Y"},
				           {"name":"Scripts","url":"rest/scripts","groupId":"050","target":"Y"},
				           {"name":"Operations","url":"rest/operations","groupId":"050","target":"Y"},
				           {"name":"Script Bundles","url":"rest/scriptbundles","groupId":"050","target":"Y"},
				           {"name":"Report Definitions","url":"rest/reportdefinitions","groupId":"060","target":"Y"},
				           {"name":"Generated Reports","url":"rest/generatedreports","groupId":"060","target":"Y"},
				           {"name":"Node List","url":"rest/nwnodelist","groupId":"070","target":"Y"},
				           {"name":"Search","url":"rest/nwsearch","groupId":"070","target":"Y"},
				           {"name":"Outages","url":"rest/nwoutages","groupId":"070","target":"Y"},
				           {"name":"Dashboard","url":"rest/nwdashboard","groupId":"070","target":"Y"},
				           {"name":"Events","url":"rest/nwevents","groupId":"070","target":"Y"},
				           {"name":"Alarms","url":"rest/nwalarms","groupId":"070","target":"Y"},
				           {"name":"Notifications","url":"rest/nwnotifications","groupId":"070","target":"Y"},
				           {"name":"Assets","url":"rest/nwassets","groupId":"070","target":"Y"},
				           {"name":"Reports","url":"rest/nwresports","groupId":"070","target":"Y"},
				           {"name":"Charts","url":"rest/nwcharts","groupId":"070","target":"Y"},
				           {"name":"Topology","url":"rest/nwtopology","groupId":"070","target":"Y"},
				           {"name":"Admin","url":"rest/nwadmin","groupId":"070","target":"Y"},
				           {"name":"Config Files Management","url":"rest/cfmanagement","groupId":"080","target":"Y"},
				           {"name":"Job Management","url":"rest/jobmanagement","groupId":"090","target":"Y"},
				           {"name":"Roles","url":"rest/roles","groupId":"100","target":"Y"},
				           {"name":"User Accounts","url":"rest/useraccounts","groupId":"100","target":"Y"},
				           {"name":"Remote Profiles","url":"rest/remoteprofiles","groupId":"100","target":"Y"},
				           {"name":"User Sessions","url":"rest/usersessions","groupId":"100","target":"Y"}],
				           "sessionBean":{"userId":"super","userCode":"super","loginDate":1381207878170,"busiSys":null}
			}
		}
	};
});